jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: dotnet build
  # test: xunit + coverlet
  # analyze: sonarcloud = static code analysis
  # package: docker image

name: ci-pipeline

on: push
